kv_namespaces = [
    { binding = "KV_DATA", id = "f1bf8614eb0247ecb5e870200c531bcd" },
    { binding = "eve-reactions-endpoints", id = "17fda7ccf69547a9b679d139571222ee" }
]

d1_databases = [
    { binding = "DB", database_id = "33adc73f-d9df-4107-b072-ad72401f890a", preview_database_id = "288fb95c-1ec0-4ad8-b08b-cc499bba5631", database_name = "eve-reactions" }
]